### ISSUE TITLE
Pruning when performing HPO for TNTM (and CTM)

### ISSUE THREAD

**Issue by ArikReuter** [AnFreTh/STREAM#59]
When tuning TNTM, some trials are pruned with, for example, the message "[I 2024-08-06 18:41:49,776] Trial 14 pruned. Trial was pruned at epoch 0.
"and "Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.model_summary.ModelSummary'>]. Skipping setting a default `ModelSummary` callback."

Is this expected?

**Comment by AnFreTh** [comment]
This: "Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.model_summary.ModelSummary'>]. Skipping setting a default ModelSummary callback."

is expected. Pruning at epoch 0 is unusual. We can adapt the MedianPruner to have a minimum number of epochs. 

Could you also give details on the dataset? Was it performed on the DummyDataset?

**Comment by ArikReuter** [comment]
The error does occur on the DummyDataset, but the configuration itself does not seem to cause a problem. Even if a config. leads to pruning, it can be used to fit the model itself

**Comment by AnFreTh** [comment]
I will close this issue, since I did not experience any issues with any of the models on a real dataset. Lets reopen, when we find these problems again
